import { chromium } from 'playwright';
const site = 'https://d3f7s31xicsud5.cloudfront.net';
const shotDir = '/Users/ruofeima/code/gamelift-workshop/scripts/shots/';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 960, height: 640 } });
await page.goto(site);
await page.waitForSelector('#name', { timeout: 15000 });
await page.fill('#name', `Tiles${Date.now() % 100000}`);
await page.fill('#password', 'gamelift');
await page.keyboard.press('Enter');
await page.waitForFunction(() => window.__game?.scene.isActive('Lobby'), null, { timeout: 20000 });
await new Promise((r) => setTimeout(r, 2000));
await page.screenshot({ path: `${shotDir}tiles-1-lobby.png` });
await page.evaluate(() => window.__game.scene.getScene('Lobby').scene.start('Shop'));
await new Promise((r) => setTimeout(r, 2500));
await page.screenshot({ path: `${shotDir}tiles-2-shop.png` });
await browser.close();
console.log('done');
